require('dotenv').config({ path: '.env' })

const cluster = require('cluster')
const express = require('express')
const consign = require('consign')
const socket = require('socket.io')
const http = require('http')

const app = express()
const server = http.createServer(app)
const io = socket(server)
consign({ cwd: 'src' })
  .include('core/mongo.js')
  .then('model')
  .then('repository')
  .then('core/auth.js')
  .then('core/utils.js')
  .then('middleware/cors.js')
  .then('middleware/bodyParser.js')
  .then('middleware/morgan.js')
  .then('middleware/validator.js')
  .then('middleware/auth.js')
  .then('scope')
  .then('routes')
  .then('middleware/error.js')
  .then('core/socket.js')
  .then('core/boot.js')
  .into(app, io, server)
