version: "3"

services: 
    nginx:
        image: nginx:1.17.8-alpine
        container_name: nginx
        volumes: 
            - ./nginx.default.conf:/etc/nginx/conf.d/default.conf
        ports: 
            - "8000:80"
    
    node1:
        image: nginx:1.17.8-alpine
        container_name: node1
        volumes: 
            - ./node1.index.html:/usr/share/nginx/html/index.html
            - ./node.default.conf:/etc/nginx/conf.d/default.conf
            - ./node.nginx.conf:/etc/nginx/nginx.conf
            - ./node1.log:/var/log/nginx/host.access.log
    
    node2:
        image: nginx:1.17.8-alpine
        container_name: node2
        volumes: 
            - ./node2.index.html:/usr/share/nginx/html/index.html
            - ./node.default.conf:/etc/nginx/conf.d/default.conf
            - ./node.nginx.conf:/etc/nginx/nginx.conf
            - ./node2.log:/var/log/nginx/host.access.log