# Generated by Django 2.1.5 on 2019-02-02 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('code', models.TextField()),
                ('lineos', models.BooleanField(default=False)),
                ('language', models.CharField(choices=[('1', 'language1'), ('2', 'language2')], default='language1', max_length=100)),
                ('style', models.CharField(choices=[('1', 'style1'), ('2', 'style2')], default='style1', max_length=100)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
