Vagrant.configure('2') do |config|
  config.vm.box = 'hashicorp/bionic64'
  config.vm.network :forwarded_port, guest: 3000, host: 3000
  config.vm.provision :ansible_local do |ansible|
    ansible.playbook = 'playbook.yaml'
  end
end
