version: '3'
services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile-api
    ports:
      - 8080:8080
  web:
    build:
      context: .
      dockerfile: Dockerfile-web
    ports:
      - 80:3000
    depends_on: 
      - api